In [53]:
from GF2 import one
from itertools import combinations, chain
from functools import reduce

In [106]:
# 2.9.29
alpha1 = [one, one, 0, 0, one, one]
alpha2 = [one, 0, one, 0, one, 0]
alpha3 = [one, one, one, 0, one, one]
alpha4 = [0, 0, one, one, 0, 0]


def vector_add(v1, v2):
    return [sum(pair) for pair in zip(v1, v2)]


def generate_combo_sums(alphas, combo_length): 
    combo_sums = []
    for combo in combinations(alphas, combo_length):
        combo_list = list(combo)
        combo_list.insert(0, [0, 0, 0, 0, 0, 0])
        print(f'{reduce(vector_add, combo_list)}: {combo}')

        
alphas = [alpha1, alpha2, alpha3, alpha4]
for n in range(1, len(alphas) + 1):
    generate_combo_sums(alphas, n)

[one, one, 0, 0, one, one]: ([one, one, 0, 0, one, one],)
[one, 0, one, 0, one, 0]: ([one, 0, one, 0, one, 0],)
[one, one, one, 0, one, one]: ([one, one, one, 0, one, one],)
[0, 0, one, one, 0, 0]: ([0, 0, one, one, 0, 0],)
[0, one, one, 0, 0, one]: ([one, one, 0, 0, one, one], [one, 0, one, 0, one, 0])
[0, 0, one, 0, 0, 0]: ([one, one, 0, 0, one, one], [one, one, one, 0, one, one])
[one, one, one, one, one, one]: ([one, one, 0, 0, one, one], [0, 0, one, one, 0, 0])
[0, one, 0, 0, 0, one]: ([one, 0, one, 0, one, 0], [one, one, one, 0, one, one])
[one, 0, 0, one, one, 0]: ([one, 0, one, 0, one, 0], [0, 0, one, one, 0, 0])
[one, one, 0, one, one, one]: ([one, one, one, 0, one, one], [0, 0, one, one, 0, 0])
[one, 0, 0, 0, one, 0]: ([one, one, 0, 0, one, one], [one, 0, one, 0, one, 0], [one, one, one, 0, one, one])
[0, one, 0, one, 0, one]: ([one, one, 0, 0, one, one], [one, 0, one, 0, one, 0], [0, 0, one, one, 0, 0])
[0, 0, 0, one, 0, 0]: ([one, one, 0, 0, one, one], [one, one, one, 0, on

In [112]:
x = [1, 2, 3, 4]
x[-1:-2:-1]

[4]

In [10]:
# 2.11.3
from vec import Vec

def zero_vec(D):
    return Vec(D, {})

def triangulat_solve_n(rowlist, b):
    D = rowlist[0].D
    n = len(D)
    x = zero_vec(D)

    for i in reversed(range(n)):  # remember, indicies can go backward too
        x[i] = (b[i] - row_list[i] * x)/row_list[i][i]
    return x

D = {0, 1, 2, 3}
row_list = [Vec(D, {0: 1, 1: 0.5, 2: -2, 3: 4}),
            Vec(D, {0: 0, 1: 3, 2: 3, 3: 2}),
            Vec(D, {0: 0, 1: 0, 2: 1, 3: 5}),
            Vec(D, {0: 0, 1: 0, 2: 0, 3: 2})]
b = [-8, 3, -4, 6]
print(triangulat_solve_n(row_list, b))


   0  1   2 3
-------------
 -67 18 -19 3


In [2]:
import vec
x = vec.Vec({1, 2}, {1: 3, 2: 4})
y = vec.Vec({1, 2}, {1: 5, 2: 6})
x[2]

4

In [152]:
# 2.11.3 reversed vectors instead of indicies
def triangulat_solve_n(rowlist, b):
    b.reverse()
    rowlist = [list(reversed(row)) for row in reversed(rowlist)]
    x = [0] * len(rowlist[0])
    for i in range(len(x)):
        x[i] = (b[i] - dot_product(rowlist[i], x))/rowlist[i][i]
    return list(reversed(x))

row_list = [[1, 0.5, -2, 4], [0, 3, 3, 2], [0, 0, 1, 5], [0, 0, 0, 2]]
b = [-8, 3, -4, 6]
triangulat_solve_n(row_list, b)

[-67.0, 18.0, -19.0, 3.0]

In [6]:
with open('voting_record_dump109.txt') as f:
    voting_records = list(f)

voting_dict = create_voting_dict(voting_records)

In [4]:
# 2.12.1
def create_voting_dict(strlist):
    voting_dict = {}
    for senator_str in strlist:
        split_str = senator_str.split()
        last_name = split_str[0]
        votes = list(map(int, split_str[3:]))
        voting_dict[last_name] = votes
    
    return voting_dict

In [167]:
def list_dot(u, v):
    return sum(u_i * v_i for u_i, v_i in zip(u, v))

In [168]:
import math
list_dot([-math.sqrt(2)/2, math.sqrt(2)/2], [math.sqrt(2)/2, -math.sqrt(2)/2])

-1.0000000000000002

In [10]:
# 2.12.2
def policy_compare(sen_a, sen_b, voting_dict):
    return list_dot(voting_dict[sen_a], voting_dict[sen_b])

policy_compare('Feingold', 'Specter', voting_dict)    

11

In [36]:
print('Feingold:', voting_dict['Feingold'])
print('Specter:', voting_dict['Specter'])

Feingold: [-1, -1, 1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1]
Specter: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 0, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [14]:
# 2.12.3
def most_similar(sen, voting_dict):
    other_senators = voting_dict.copy()
    del other_senators[sen]
    return max(other_senators.keys(), 
               key=lambda sen_b: policy_compare(sen, sen_b, voting_dict))

most_similar('Feingold', voting_dict)

'Boxer'

In [17]:
# 2.12.4
def least_similar(sen, voting_dict):
    other_senators = voting_dict.copy()
    del other_senators[sen]
    return min(other_senators.keys(), 
               key=lambda sen_b: policy_compare(sen, sen_b, voting_dict))

least_similar('Feingold', voting_dict)

'Inhofe'

In [18]:
# 2.12.5
most_similar('Chafee', voting_dict)

'Jeffords'

In [19]:
least_similar('Santorum', voting_dict)

'Feingold'

In [23]:
# 2.12.6
policy_compare('Domenici', 'Bingaman', voting_dict)

23

In [33]:
# 2.12.7
democrat_senators = set()
for senator_str in voting_records:
    split_str = senator_str.split()
    last_name = split_str[0]
    party = split_str[1]
    if party == 'D':
        democrat_senators.add(last_name)

In [36]:
democrat_senators

{'Akaka',
 'Baucus',
 'Bayh',
 'Biden',
 'Bingaman',
 'Boxer',
 'Byrd',
 'Cantwell',
 'Carper',
 'Clinton',
 'Conrad',
 'Dayton',
 'Dodd',
 'Dorgan',
 'Durbin',
 'Feingold',
 'Feinstein',
 'Harkin',
 'Inouye',
 'Johnson',
 'Kennedy',
 'Kerry',
 'Kohl',
 'Landrieu',
 'Lautenberg',
 'Leahy',
 'Levin',
 'Lieberman',
 'Lincoln',
 'Mikulski',
 'Murray',
 'Nelson1',
 'Nelson2',
 'Obama',
 'Pryor',
 'Reed',
 'Reid',
 'Rockefeller',
 'Salazar',
 'Sarbanes',
 'Schumer',
 'Stabenow',
 'Wyden'}

In [26]:
import numpy as np

In [37]:
def find_average_similarity(sen, sen_set, voting_dict):
    similarities = [policy_compare(sen, sen_b, voting_dict) for sen_b in sen_set]
    return sum(similarities) / len(similarities)

In [38]:
max(voting_dict.keys(), 
    key=lambda sen: find_average_similarity(sen, democrat_senators, voting_dict))

'Biden'

In [42]:
# 2.12.8
def vector_add(u, v):
    assert len(u) == len(v)
    return [u_i + v_i for u_i, v_i in zip(u, v)]
    
    
def find_average_record(sen_set, voting_dict):
    sum_records = [0] * len(voting_dict[list(sen_set)[0]])
    for sen in list(sen_set):
        sum_records = vector_add(sum_records, voting_dict[sen])
    return [sum_record / len(sen_set) for sum_record in sum_records]

average_democrat_record = find_average_record(democrat_senators, voting_dict)
max(voting_dict.keys(), 
    key=lambda sen: list_dot(voting_dict[sen], average_democrat_record))

'Biden'

In [43]:
average_democrat_record

[-0.16279069767441862,
 -0.23255813953488372,
 1.0,
 0.8372093023255814,
 0.9767441860465116,
 -0.13953488372093023,
 -0.9534883720930233,
 0.813953488372093,
 0.9767441860465116,
 0.9767441860465116,
 0.9069767441860465,
 0.7674418604651163,
 0.6744186046511628,
 0.9767441860465116,
 -0.5116279069767442,
 0.9302325581395349,
 0.9534883720930233,
 0.9767441860465116,
 -0.3953488372093023,
 0.9767441860465116,
 1.0,
 1.0,
 1.0,
 0.9534883720930233,
 -0.4883720930232558,
 1.0,
 -0.32558139534883723,
 -0.06976744186046512,
 0.9767441860465116,
 0.8604651162790697,
 0.9767441860465116,
 0.9767441860465116,
 1.0,
 1.0,
 0.9767441860465116,
 -0.3488372093023256,
 0.9767441860465116,
 -0.4883720930232558,
 0.23255813953488372,
 0.8837209302325582,
 0.4418604651162791,
 0.9069767441860465,
 -0.9069767441860465,
 1.0,
 0.9069767441860465,
 -0.3023255813953488]

In [51]:
# 2.12.9
from itertools import combinations

In [55]:
def bitter_rivals(voting_dict):
    senator_pairs = list(combinations(voting_dict.keys(), 2))
    worst_rivals = senator_pairs[0]
    lowest_similarity = policy_compare(*worst_rivals, voting_dict)
    
    for pair in senator_pairs:
        pair_similarity = policy_compare(*pair, voting_dict)
        if pair_similarity < lowest_similarity:
            lowest_similarity = pair_similarity
            worst_rivals = pair
            
    return worst_rivals

bitter_rivals(voting_dict)

('Feingold', 'Inhofe')

In [53]:
policy_compare('Feingold', 'Inhofe', voting_dict)

-3

In [56]:
voting_dict_test = {'Klein':[-1,0,1], 'Fox-Epstein':[-1,-1,-1], 'Ravella':[0,0,1], 'Oyakawa':[1,1,1], 'Loery':[1,1,0]}
bitter_rivals(voting_dict_test)

('Fox-Epstein', 'Oyakawa')

In [57]:
# 2.12.10
republican_senators = set()
for senator_str in voting_records:
    split_str = senator_str.split()
    last_name = split_str[0]
    party = split_str[1]
    if party == 'R':
        republican_senators.add(last_name)
        
republican_senators

{'Alexander',
 'Allard',
 'Allen',
 'Bennett',
 'Bond',
 'Brownback',
 'Bunning',
 'Burns',
 'Burr',
 'Chafee',
 'Chambliss',
 'Coburn',
 'Cochran',
 'Coleman',
 'Collins',
 'Cornyn',
 'Craig',
 'Crapo',
 'DeMint',
 'DeWine',
 'Dole',
 'Domenici',
 'Ensign',
 'Enzi',
 'Frist',
 'Graham',
 'Grassley',
 'Gregg',
 'Hagel',
 'Hatch',
 'Hutchison',
 'Inhofe',
 'Isakson',
 'Kyl',
 'Lott',
 'Lugar',
 'Martinez',
 'McCain',
 'McConnell',
 'Murkowski',
 'Roberts',
 'Santorum',
 'Sessions',
 'Shelby',
 'Smith',
 'Snowe',
 'Specter',
 'Stevens',
 'Sununu',
 'Talent',
 'Thomas',
 'Thune',
 'Vitter',
 'Voinovich',
 'Warner'}

In [59]:
average_republican_record = find_average_record(republican_senators, voting_dict)

[0.9636363636363636,
 0.8181818181818182,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8181818181818182,
 0.8181818181818182,
 1.0,
 0.21818181818181817,
 0.6727272727272727,
 -0.16363636363636364,
 0.8,
 0.9090909090909091,
 0.5636363636363636,
 0.8545454545454545,
 0.9636363636363636,
 0.9272727272727272,
 0.7818181818181819,
 0.9636363636363636,
 1.0,
 1.0,
 1.0,
 -0.3090909090909091,
 0.5636363636363636,
 0.9636363636363636,
 0.8545454545454545,
 1.0,
 0.9636363636363636,
 0.8909090909090909,
 0.8,
 0.9818181818181818,
 0.9272727272727272,
 0.9818181818181818,
 0.9818181818181818,
 0.8,
 0.9636363636363636,
 0.9454545454545454,
 0.9636363636363636,
 0.9636363636363636,
 0.9636363636363636,
 0.9272727272727272,
 0.8181818181818182,
 0.9818181818181818,
 1.0,
 0.8181818181818182]

In [64]:
min(democrat_senators,
    key=lambda sen: list_dot(voting_dict[sen], average_republican_record))

'Feingold'

In [65]:
sorted(republican_senators,
    key=lambda sen: list_dot(voting_dict[sen], average_republican_record))

['Chafee',
 'Coburn',
 'Collins',
 'Snowe',
 'Sununu',
 'McCain',
 'Burr',
 'Inhofe',
 'Gregg',
 'Enzi',
 'Thomas',
 'Graham',
 'Ensign',
 'Specter',
 'Craig',
 'Coleman',
 'DeMint',
 'Vitter',
 'Martinez',
 'Crapo',
 'DeWine',
 'Voinovich',
 'Lott',
 'Dole',
 'Cornyn',
 'Shelby',
 'Thune',
 'Kyl',
 'Bunning',
 'Burns',
 'Alexander',
 'Hutchison',
 'Stevens',
 'Bennett',
 'Brownback',
 'Frist',
 'Sessions',
 'Domenici',
 'Santorum',
 'Smith',
 'Lugar',
 'Murkowski',
 'Warner',
 'Hatch',
 'Hagel',
 'Cochran',
 'Chambliss',
 'Isakson',
 'Allard',
 'McConnell',
 'Talent',
 'Allen',
 'Grassley',
 'Bond',
 'Roberts']

In [73]:
average_record = find_average_record(voting_dict.keys(), voting_dict)
sorted(voting_dict.keys(), 
       key=lambda sen: list_dot(voting_dict[sen], average_record)).index('Obama')

29

In [76]:
def count_political_opponents(sen, voting_dict):
    opponents = 0
    for sen_b in voting_dict.keys():
        if policy_compare(sen, sen_b, voting_dict) < 0:
            opponents += 1
    
    return opponents

sorted(voting_dict.keys(),
    key=lambda sen: count_political_opponents(sen, voting_dict))

['Akaka',
 'Alexander',
 'Allard',
 'Allen',
 'Baucus',
 'Bayh',
 'Bennett',
 'Biden',
 'Bingaman',
 'Bond',
 'Boxer',
 'Brownback',
 'Burns',
 'Burr',
 'Byrd',
 'Cantwell',
 'Carper',
 'Chafee',
 'Chambliss',
 'Clinton',
 'Coburn',
 'Cochran',
 'Coleman',
 'Collins',
 'Conrad',
 'Cornyn',
 'Craig',
 'Crapo',
 'Dayton',
 'DeMint',
 'DeWine',
 'Dodd',
 'Dole',
 'Domenici',
 'Dorgan',
 'Durbin',
 'Enzi',
 'Feinstein',
 'Frist',
 'Graham',
 'Grassley',
 'Gregg',
 'Hagel',
 'Harkin',
 'Hatch',
 'Hutchison',
 'Inouye',
 'Isakson',
 'Jeffords',
 'Johnson',
 'Kennedy',
 'Kerry',
 'Kohl',
 'Kyl',
 'Landrieu',
 'Lautenberg',
 'Leahy',
 'Levin',
 'Lieberman',
 'Lincoln',
 'Lott',
 'Lugar',
 'Martinez',
 'McCain',
 'McConnell',
 'Mikulski',
 'Murkowski',
 'Murray',
 'Nelson1',
 'Nelson2',
 'Obama',
 'Pryor',
 'Reed',
 'Reid',
 'Roberts',
 'Rockefeller',
 'Salazar',
 'Santorum',
 'Sarbanes',
 'Schumer',
 'Sessions',
 'Shelby',
 'Smith',
 'Snowe',
 'Specter',
 'Stabenow',
 'Stevens',
 'Talent',
 'T

In [77]:
# 2.14.2
v = np.array([2, -1, 5])
u = np.array([-1, 1, 1])
print(v + u)
print(v - u)
print(2 * v - u)
print(v + 2 * u)

[1 0 6]
[ 3 -2  4]
[ 5 -3  9]
[0 1 7]


In [81]:
# 2.14.3
from GF2 import one
v = np.array([0, one, one])
u = np.array([one, one, one])
print(v + u)
print(v + u + u)

[one 0 0]
[0 one one]


In [149]:
# 2.14.4
def str2gf2(num_str):
    return np.array([one if num == '1' else 0 for num in list(num_str)])

vectors = {
    'a': '1100000', 
    'b': '0110000', 
    'c': '0011000', 
    'd': '0001100',
    'e': '0000110',
    'f': '0000011'
}

def sum_combo(combo, vectors):
    combo_gf2 = np.array([str2gf2(vectors[label]) for label in combo])
    return combo, np.sum(combo_gf2, axis=0)


def find_combo_match(vectors, match):
    match_gf2 = str2gf2(match)
    for combo_length in range(1, len(vectors) + 1):
        for combo in combinations(vectors, combo_length):
            combo, combo_sum = sum_combo(combo, vectors)
            if all(combo_sum == match_gf2):
                return combo
    
    return 'No match found'

            
find_combo_match(vectors, '0100010')

('b', 'c', 'd', 'e')

In [108]:
from itertools import chain

In [141]:
def sum_from_letters(letters, vectors):
    gf2_vectors = [str2gf2(vectors[letter]) for letter in letters]
    return np.array(gf2_vectors).sum(axis=0)
    
    
sum_from_letters(('c', 'd', 'e'), vectors)

array([0, 0, one, 0, 0, one, 0], dtype=object)

In [150]:
# 2.14.5
vectors7 = {
    'a': '1110000', 
    'b': '0111000', 
    'c': '0011100', 
    'd': '0001110',
    'e': '0000111',
    'f': '0000011'
}

find_combo_match(vectors7, '0010010')

('c', 'd')

In [151]:
find_combo_match(vectors7, '0100010')

'No match found'

In [152]:
sum_from_letters(('c', 'd'), vectors7)

array([0, 0, one, 0, 0, one, 0], dtype=object)

In [165]:
from plotting import plot
def generate_points(v1, v2):
    a1 = np.array(v1)
    a2 = np.array(v2)
    return [list(alpha * a1 + (1 - alpha) * a2) for alpha in np.linspace(0, 1, 100)]

plot(generate_points([-1.5, 2], [3,0]), 5)

In [166]:
plot(generate_points([2, 1], [2, -2]), 5)

In [1]:
# 2.14.10
import sys
sys.path.append(r'C:\Projects\coding-the-matrix\Solution')
from vec import *

In [2]:
a = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2})
b = Vec({'a','e','i','o','u'}, {'o':4,'u':7})
c = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2,'o':4,'u':7})

In [3]:
equal(a + b, c)

True

In [4]:
import doctest
doctest.testfile(r'C:\Projects\coding-the-matrix\Solution\vec.py')

**********************************************************************
File "C:\Projects\coding-the-matrix\Solution\vec.py", line 8, in vec.py
Failed example:
    v = Vec({'a','b','c', 'd'},{'a':2,'c':1,'d':3})
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\nguye\Anaconda3\lib\doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest vec.py[0]>", line 1, in <module>
        v = Vec({'a','b','c', 'd'},{'a':2,'c':1,'d':3})
    NameError: name 'Vec' is not defined
**********************************************************************
File "C:\Projects\coding-the-matrix\Solution\vec.py", line 9, in vec.py
Failed example:
    v['d']
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\nguye\Anaconda3\lib\doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest vec.py[1]>", line 1, in <module>
        v['d']
    NameError: name 'v' is not defined
**********************

TestResults(failed=55, attempted=55)