In [7]:
import sys
sys.path.insert(0, r'C:\Projects\coding-the-matrix\Solution')

import numpy as np
from vec import *

In [14]:
def vec_from_list(l):
    D = set(range(len(l)))
    return Vec(D, dict(zip(D, l)))

In [15]:
vec_from_list([2, 3, 4])

Vec({0, 1, 2},{0: 2, 1: 3, 2: 4})

In [1]:
# 3.1.7
def lin_comb(vlist, clist):
    return [c * v for c, v in zip(clist, vlist)]

lin_comb([Vec({1, 2}, {1: 3, 2: 4}), Vec({1, 2}, {1: 7, 2: 8})], [5, 6])

In [22]:
# 3.2.12
a = np.array([2, 0, 1])
b = np.array([1, 0, 2])
c = np.array([2, 2, 2])
d = np.array([0, 1, 0])
for x in np.arange(-5, 5.1, 0.5):
    for y in np.arange(-5, 5.1, 0.5):
        for z in np.arange(-5, 5.1, 0.5):
            for t in np.arange(-5, 5.1, 0.5):
                if np.all(x * a + y * b + z * c + t * d == np.array([0, 2, 0])):
                    print(x, y, z, t)

-2.0 -2.0 3.0 -4.0
-1.0 -1.0 1.5 -1.0
0.0 0.0 0.0 2.0
1.0 1.0 -1.5 5.0


In [21]:
-a - b - d + c * 3/2

array([ 0.,  2.,  0.])

In [25]:
# 3.2.13
def standard(D, one):
    return [Vec(D, {k: one}) for k in range(len(D))]

In [26]:
standard({4, 2, 5, 1}, 9)

[Vec({1, 2, 4, 5},{0: 9}),
 Vec({1, 2, 4, 5},{1: 9}),
 Vec({1, 2, 4, 5},{2: 9}),
 Vec({1, 2, 4, 5},{3: 9})]

In [39]:
# 3.2.15
a = np.array([1, 1])
b = np.array([1, -1])
c = np.array([0, 1])
for x in np.arange(-5, 5.1, 0.5):
    for y in np.arange(-5, 5.1, 0.5):
        for z in np.arange(-5, 5.1, 0.5):
            if all(a * x + b * y + c * z == np.array([1, 0])):
                print(x, y, z)

-2.0 3.0 5.0
-1.5 2.5 4.0
-1.0 2.0 3.0
-0.5 1.5 2.0
0.0 1.0 1.0
0.5 0.5 0.0
1.0 0.0 -1.0
1.5 -0.5 -2.0
2.0 -1.0 -3.0
2.5 -1.5 -4.0
3.0 -2.0 -5.0


In [45]:
# 3.2.16
e1 = [1, 0, 0]
e2 = [0, 1, 0]
e3 = [0, 0, 1]
a = [1, 1, 1]
b = [0.4, 1.3, -2.2]
e1, e2, e3, a, b = map(np.array, [e1, e2, e3, a, b])

In [46]:
e1

array([1, 0, 0])

In [58]:
c1 = set()
coeff_range = np.arange(-5, 5.1, 0.1)
for x in coeff_range:
    for y in coeff_range:
        for z in coeff_range:
            if z != 0:
                c1.add(tuple((e1 - x * a - y * b)/z))
                
c2 = set()
for x in coeff_range:
    for y in coeff_range:
        for z in coeff_range:
            if z != 0:
                c2.add(tuple((e2 - x * a - y * b)/z))
                
c3 = set()
for x in coeff_range:
    for y in coeff_range:
        for z in coeff_range:
            if z != 0:
                c3.add(tuple((e3 - x * a - y * b)/z))
                
c1 & c2

set()

In [59]:
a + b

array([ 1.4,  2.3, -1.2])

# 3.3 Geometry of sets of vector

In [13]:
D = set(range(3))
u = Vec(D, dict(zip(D, [1, 0, 1.65])))
v = Vec(D, dict(zip(D, [0, 1, 1])))
for a in range(-5, 5):
    for b in range(-5, 5):
        if a * u + b * v == Vec(D, dict(zip(D, [0, 0, 0]))):
            print('a: {}, b: {}'.format(a, b))

a: 0, b: 0


In [17]:
def cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
         a[2]*b[0] - a[0]*b[2],
         a[0]*b[1] - a[1]*b[0]]

    return c

cross([1, 0, 1.65], [0, 1, 1])

[-1.65, -1.0, 1]

# Problems

In [2]:
# 3.8.1
def vec_select(veclist, k):
    return [v for v in veclist if v[k] == 0]

In [36]:
D = {'a','b','c'}
v1 = Vec(D, {'a': 1})
v2 = Vec(D, {'a': 0, 'b': 1})
v3 = Vec(D, {'b': 2})
v4 = Vec(D, {'a': 10, 'b': 10})
vec_select([v1, v2, v3, v4], 'a')

[Vec({'c', 'a', 'b'},{'b': 1}), Vec({'c', 'a', 'b'},{'b': 2})]

In [16]:
# 3.8.2
def vec_sum(veclist, D):
    return sum(veclist)

In [35]:
D = {'a','b','c'}
v1 = Vec(D, {'a': 1})
v2 = Vec(D, {'a': 0, 'b': 1})
v3 = Vec(D, {        'b': 2})
v4 = Vec(D, {'a': 10, 'b': 10})
vec_sum([v1, v2, v3, v4], D)

Vec({'b', 'c', 'a'},{'b': 13, 'a': 11})

In [42]:
# 3.8.3
def vec_select_sum(veclist, k, D):
    return vec_sum(vec_select(veclist, k), D)

In [43]:
D = {'a','b','c'}
v1 = Vec(D, {'a': 1})
v2 = Vec(D, {'a': 0, 'b': 1})
v3 = Vec(D, {'b': 2})
v4 = Vec(D, {'a': 10, 'b': 10})
vec_select_sum([v1, v2, v3, v4], 'a', D)

Vec({'c', 'a', 'b'},{'b': 3})